# Generated by Django 6.0 on 2025-12-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='video_link',
            field=models.URLField(blank=True, help_text='รองรับลิงก์จาก YouTube', null=True),
        ),
    ]
